#!/bin/bash

display_help() {
   echo "======================================"
   echo "   Trivia APP Local Runner CLI"
   echo "======================================"
   echo "Syntax: local-run [command]"
   echo
   echo "---commands---"
   echo "help               Print CLI help"
   echo "start              Start Trivia local environment"
   echo "cli                Enter Trivia CLI in local environment"
   echo "stop               Stop Trivia local environment"
   echo
}

build_image() {
   docker compose build
}

start() {
   docker compose -p trivia-rest-api up -d
}

cli() {
   docker exec -it trivia-rest-api-web-1 bash
}

stop() {
   docker compose -p trivia-rest-api down
}


case "$1" in
build-and-start)
   build_image
   start $2
   ;;
start)
   start $2
   ;;
cli)
   cli
   ;;
stop)
   stop
   ;;
*)
   echo "No command specified, displaying help"
   display_help
   ;;
esac
